server:
  port: 8761
spring:
  application:
    name: serviceregistry
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8090
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"