spring:
  application:
    name: employee-service
  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:8090
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://employeedbuser:employeetest2018@ds257485.mlab.com:57485/CloudFoundry_99nkbst4_nmatj8k4
  redis:
    host: edis-14932.c16.us-east-1-3.ec2.cloud.redislabs.com
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    enabled: true
server:
  port: 7676
