spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
          - Path=/**
        filters:
          - RewritePath=/(?<RID>.*),/$\{RID}
      discovery:
        locator:
          enabled: true

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

server:
  port: 8080
